import { test } from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
const bundle = await build({stdin:{contents:"export * from './src/services/add-vocabulary-word'; export * from './src/editor/hiwords-document'; export {TFile} from 'obsidian';",resolveDir:process.cwd()},bundle:true,write:false,format:'esm',platform:'node',define:{window:'globalThis'},plugins:[{name:'boundary',setup(b){b.onResolve({filter:/^obsidian$/},()=>({path:'obsidian',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:'export class TFile { constructor(path){this.path=path;this.extension=path.split(".").pop();} }'}));}}]});
const api=await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString('base64')}`);
function fixture(){const file=new api.TFile('words.hiwords');let data=api.serializeHiWordsPack(api.createEmptyHiWordsPack('Words'));let chain=Promise.resolve();let reloads=0;const plugin={settings:{vocabularyBooks:[{path:file.path,enabled:true,name:'Words'}]},app:{workspace:{getLeavesOfType:()=>[]},vault:{getAbstractFileByPath:()=>file,read:async()=>data,process:async(_,fn)=>{chain=chain.then(()=>{data=fn(data)});await chain;}}},vocabularyManager:{reloadVocabularyBook:async()=>reloads++},refreshHighlighter(){}};return {file,plugin,read:()=>JSON.parse(data),reloads:()=>reloads};}
test('adding hiwords preserves definitions, aliases and existing content under concurrent writes',async()=>{const f=fixture();await Promise.all(['hello','world'].map(word=>api.addVocabularyWord(f.plugin,f.file.path,{word,definition:'**释义**\nline two',aliases:[word+'s']})));const pack=f.read();assert.equal(pack.cards.length,2);assert.equal(pack.cards[0].data.meanings[0].definition,'**释义**\nline two');assert.deepEqual(pack.cards[0].aliases,['hellos']);assert.equal(f.reloads(),2);assert.equal(api.parseHiWordsEditorDocument(JSON.stringify(pack)).kind,'hiwords');await assert.rejects(api.addVocabularyWord(f.plugin,f.file.path,{word:'HELLO',definition:'replace'}));assert.equal(f.read().cards.length,2);});
test('open editor receives insertion instead of overwriting its unsaved document',async()=>{const f=fixture();let called;f.plugin.app.workspace.getLeavesOfType=()=>[{view:{file:f.file,appendVocabularyWord:async input=>{called=input;return true}}}];await api.addVocabularyWord(f.plugin,f.file.path,{word:'hello',definition:'meaning'});assert.equal(called.word,'hello');assert.equal(f.read().cards.length,0);});
test('only enabled word-format destinations are accepted',async()=>{const f=fixture();assert.equal((await api.getAddableVocabularyBooks(f.plugin)).length,1);f.plugin.settings.vocabularyBooks[0].enabled=false;assert.equal(await api.addVocabularyWord(f.plugin,f.file.path,{word:'hello',definition:''}),false);const pack=api.createEmptyHiWordsPack('Concepts');pack.cardKind='knowledge.concept';assert.throws(()=>api.appendWordCard(pack,{word:'hello',definition:''}));});
